[package]
name = "rsbtc"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
chrono = { version = "0.4.42", features = ["serde"] }
thiserror = "2.0.17"

[workspace]
resolver = "2"
members = ["lib", "miner", "node", "wallet",]
